/* (c) mg */

#ifndef MB_GAMEPADBUTTONS_H_INCLUDED
#define MB_GAMEPADBUTTONS_H_INCLUDED


#if defined(__EMSCRIPTEN__)

typedef enum M_GamepadButton {
    M_GAMEPADBUTTON_A   = 0,
    M_GAMEPADBUTTON_B   = 1,
    M_GAMEPADBUTTON_X   = 2,
    M_GAMEPADBUTTON_Y   = 3,
    M_GAMEPADBUTTON_LEFT_BUMPER   = 4,
    M_GAMEPADBUTTON_RIGHT_BUMPER   = 5,
    M_GAMEPADBUTTON_INTERNAL_LEFT_TRIGGER = 6, // only in emscripten. we will map to axis manually with 0.0 or 1.1 value
    M_GAMEPADBUTTON_INTERNAL_RIGHT_TRIGGER = 7, // only in emscripten. we will map to axis manually with 0.0 or 1.1 value
    M_GAMEPADBUTTON_BACK   = 8,
    M_GAMEPADBUTTON_START   = 9,
    M_GAMEPADBUTTON_LEFT_THUMB   = 10,
    M_GAMEPADBUTTON_RIGHT_THUMB   = 11,
    M_GAMEPADBUTTON_DPAD_UP   = 12,
    M_GAMEPADBUTTON_DPAD_DOWN   = 13,
    M_GAMEPADBUTTON_DPAD_LEFT   = 14,
    M_GAMEPADBUTTON_DPAD_RIGHT   = 15,
    M_GAMEPADBUTTON_GUIDE   = 16,
    M_NUM_GAMEPADBUTTONS   = 17,
} M_GamepadButton;

#else

// Same as GLFW3
typedef enum M_GamepadButton {
    M_GAMEPADBUTTON_A   = 0,
    M_GAMEPADBUTTON_B   = 1,
    M_GAMEPADBUTTON_X   = 2,
    M_GAMEPADBUTTON_Y   = 3,
    M_GAMEPADBUTTON_LEFT_BUMPER   = 4,
    M_GAMEPADBUTTON_RIGHT_BUMPER   = 5,
    M_GAMEPADBUTTON_BACK   = 6,
    M_GAMEPADBUTTON_START   = 7,
    M_GAMEPADBUTTON_GUIDE   = 8,
    M_GAMEPADBUTTON_LEFT_THUMB   = 9,
    M_GAMEPADBUTTON_RIGHT_THUMB   = 10,
    M_GAMEPADBUTTON_DPAD_UP   = 11,
    M_GAMEPADBUTTON_DPAD_RIGHT   = 12,
    M_GAMEPADBUTTON_DPAD_DOWN   = 13,
    M_GAMEPADBUTTON_DPAD_LEFT   = 14,
    M_NUM_GAMEPADBUTTONS   = 15,
} M_GamepadButton;

#endif


#endif  /* MB_GAMEPADBUTTONS_H_INCLUDED */

