if(NOT EXISTS "C:/work/lyke/lyke2d/external/ode-0.16.2/install_manifest.txt")
	message(FATAL_ERROR "Cannot find install manifest: \"C:/work/lyke/lyke2d/external/ode-0.16.2/install_manifest.txt\"")
endif()

file(READ "C:/work/lyke/lyke2d/external/ode-0.16.2/install_manifest.txt" FILES)
string(REGEX REPLACE "\n" ";" FILES "${FILES}")

foreach(FILE ${FILES})
	message(STATUS "Uninstalling: ${FILE}")
	if(EXISTS "${FILE}")
		file(REMOVE ${FILE})
	elseif(IS_SYMLINK "${FILE}")
		file(REMOVE ${FILE})
	else()
		message(STATUS "File \"${FILE}\" does not exist.")
	endif()
endforeach()
